#!/bin/sh
# This script is used for calling ANT by Shell
function callANT()
{
# -----------------------------------------------
# defining the configuration required to run Ant
# -----------------------------------------------
JAVA_HOME=/usr/java/jdk1.6.0_38
export JAVA_HOME

CVS_RSH=/usr/bin/ssh
export CVS_RSH

CVS_SERVER=/bin/cvs.exe
export CVS_SERVER

ANT_HOME=/usr/local/share/apache-ant-1.9.0

# classpath used to start Ant
CLASSPATH=$JAVA_HOME/lib/tools.jar
CLASSPATH=$CLASSPATH:$ANT_HOME/lib/ant.jar
CLASSPATH=$CLASSPATH:$ANT_HOME/lib/ant-launcher.jar
CLASSPATH=$CLASSPATH:$ANT_HOME/lib/mail.jar
CLASSPATH=$CLASSPATH:$ANT_HOME/lib/activation.jar
export CLASSPATH

# ------------------------
# invoking the Ant script
# ------------------------

$JAVA_HOME/bin/java \
     -Dant.home=$ANT_HOME \
     org.apache.tools.ant.Main \
	 -verbose \
     -buildfile "$buildfile" \
	 -logfile "$logfile" "$target"
#    -propertyfile ./projects/$APPLICATION_NAME.deploy.properties 
echo "exit code is [$?]"
}

case $1 in
  "back-mail")
			buildfile=/home/svn/bin/ant-scirpt/back-mail.xml
			logfile=/home/svn/back-up/mail-logs/back-mail.log
			if [ ! $2 = "" ] 
			then
				target="$2"
			else
				target="mail" # usually set as the default targetm cannot be blank
			fi
			callANT
			;;
	*)
			echo "No such kind of ant scirpt .."
			exit 1
			;;
esac
