#!/usr/bin/bash
# This script is used for codes updated in local-CVS daily
echo "Rationale is cvs co/up project folder"
echo ""
cvsroot=":sspi:jack.wang@192.168.2.200:/1fb"
bcvs="/cygdrive/d/BleumCVS"
jkcvs="/cygdrive/d/JKCVS"

if [ ! -d $bcvs ]
  then
	mkdir $bcvs
	source ~/bin/go $bcvs
	cvs -d $cvsroot co -P 1fbodc affinity csmaintenance fs services
else
	source ~/bin/go $bcvs
	cvs -d $cvsroot up -A -d -P 1fbodc affinity csmaintenance fs services
fi

if [ ! -d $jkcvs ]
  then
	mkdir $jkcvs
	source ~/bin/go $jkcvs
	cvs -d $cvsroot co -P -r AFF_3_50_Porting affinity/sourcecode/afcollagent affinity/sourcecode/afcsragent affinity/sourcecode/afshared services/Sourcecode 
	cvs -d $cvsroot co -P -r FS_7_50 fs/Sourcecode/fscm/src fs/Sourcecode/fscm/war fs/Sourcecode/fsshared/src fs/Sourcecode/fssplashcontent/src fs/Sourcecode/fssplashcontent/war
	cvs -d $cvsroot co -P -r FS_7_50 services $jkcvs/fs_services
	else
	source ~/bin/go $jkcvs
	cvs -d $cvsroot up -d -P -r AFF_3_50_Porting affinity/sourcecode/afcollagent affinity/sourcecode/afcsragent affinity/sourcecode/afshared services/Sourcecode
    cvs -d $cvsroot up -d -P -r FS_7_50 fs/Sourcecode/fscm/src fs/Sourcecode/fscm/war fs/Sourcecode/fsshared/src fs/Sourcecode/fssplashcontent/src fs/Sourcecode/fssplashcontent/war
	source ~/bin/go fs_services && cvs -d $cvsroot up -d -P -r FS_7_50 services && source ~/bin/go $jkcvs
fi