#!/usr/bin/bash
# This script is used for calling ANT by Shell
function callANT()
{
# -----------------------------------------------
# defining the configuration required to run Ant

# set java.home and ant.home
JAVA_HOME="D:\Program Files\Java\JDK"
export JAVA_HOME
ANT_HOME="D:\Program Files\ant"

# classpath used to start Ant
#CLASSPATH="D:\Program Files\Java\JDK\lib\tool.jar;D:\Program Files\ant\lib\ant.jar;D:\Program Files\ant\lib\ant-launcher.jar"
CLASSPATH="$JAVA_HOME\lib\tool.jar"
CLASSPATH="$CLASSPATH;$ANT_HOME\lib\ant.jar"
CLASSPATH="$CLASSPATH;$ANT_HOME\lib\ant-launcher.jar"
export CLASSPATH

# PATH="$ANT_HOME/bin:$PATH"
# export PATH
# echo $JAVA_HOME
# echo $ANT_HOME
# echo $CLASSPATH
# -----------------------------------------------

"$JAVA_HOME"/bin/java \
     -Dant.home="$ANT_HOME" \
     org.apache.tools.ant.Main \
	 -verbose \
     -buildfile "$buildfile" \
	 -logfile "$logfile" "$target"
echo "exit code is [$?]"
}

case $1 in
  "sync-mail")
			buildfile="D:\sync\sync logs\script\sync-mail.xml"
			logfile="D:\sync\sync logs\script\backup-mail.log"
			if [ ! $2 = "" ] 
			then
				target="$2"
			else
				target="mail" # usually set as the default targetm cannot be blank
			fi
			callANT
			;;
	*)
			echo "No such kind of ant scirpt .."
			exit 1
			;;
esac