#!/usr/bin/bash
# This script is used for simple check whether any codes updated in ito-CVS when generating file list
echo "Rationale is cvs rdiff -r -s tagname -r HEAD project folder"
echo ""
echo "Please Link to VPN first!"
echo "first param is ito cvs module (cs/af/fs750/fs/services/ouputxml/databasexml/afservice ...)"
echo "second param is the previous tag name(e.g. BLEUM_CS_RC_08212012_1)"
echo "third param is the target tag name you want to update to ( usually Head )"
echo ""
module="$1"
previoustag=$2
currenttag=$3
file=~/update_filelist_ito.txt
itocvsroot=":ext:bbu@ito-as1.1fb.net:/vb/cvs"

case "$module" in
  "cs")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    cs/src cs/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoCS src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "af")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    afcollagent/src afcollagent/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoAFcoll src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    afcsragent/src afcsragent/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoAFcsr src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee -a $file | wc -l|awk '{print $0-1}'
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    afshared/src afshared/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoAFShared src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee -a $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '/^\-/ {print $0} /^[A-Za-z0-9]/ {print "M    "$0} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-3}'
    ;;
  "af360")
    echo "Current AF3.60 project, fsshared and services coding on branch:'AFF_3_60_CAT1'..."
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    afcollagent/src afcollagent/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoAFcoll src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    afcsragent/src afcsragent/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoAFcsr src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee -a $file | wc -l|awk '{print $0-1}'
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    afshared/src afshared/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoAFShared src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee -a $file | wc -l|awk '{print $0-1}'
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag fsshared/src | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoFsshared src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    if [ $currenttag = "HEAD" ]
	 then
      currenttag="AFF_3_60_CAT1"
    fi
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    services/src services/mapping | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoServices src/mapping--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'    
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '/^\-/ {print $0} /^[A-Za-z0-9]/ {print "M    "$0} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-5}'
    ;;    
  "afservice")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    afservice/src | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoafservice src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "services")
    echo "Start diff from $2 ..."
    echo "ignore com/onefbusa/services/common/external/biz/channel/textbanking/ThruDatable.java"
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    services/src services/mapping | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoServices src/mapping--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "fsshared")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag fsshared/src | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoFsshared src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "fs750")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    fscm/src fscm/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoFscm src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    fsshared/src | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoFsshared src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee -a $file | wc -l|awk '{print $0-1}'
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    fssplashcontent/src fssplashcontent/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoFssplashcontent src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee -a $file | wc -l|awk '{print $0-1}'
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    services/src services/mapping | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoservices src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee -a $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '/^\-/ {print $0} /^[A-Za-z0-9]/ {print "M    "$0} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-4}'
    ;;
  "fs")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    fsagent/src fsagent/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoFsagent src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    fscm/src fscm/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoFscm src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee -a $file | wc -l|awk '{print $0-1}'
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    fsshared/src | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoFsshared src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee -a $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '/^\-/ {print $0} /^[A-Za-z0-9]/ {print "M    "$0} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-3}'
    ;;
  "fssplashcontent")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    fssplashcontent/src fssplashcontent/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoFssplashcontent src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "textbankingservice")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    textbankingservice/src | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itotextbankingservice src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "emailservice")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    emailservice/src | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoemailservice src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "autopayservice")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    autopayservice/src | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoautopayservice src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "accountservice")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    accountservice/src | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoautopayservice src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "phoneprocessor")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    phoneprocessor/src phoneprocessor/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itophoneprocessor src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "outputxml")
    echo "Start diff from $2 ..."
    echo "current we only focus on: 1fbbizprocess, ftebizprocess, accountbizprocess, autopaybizprocess, emailbizprocess "
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    outputXmlFiles | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--ito outputXmlFiles--",d,"----------"}{{for(k = 2; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "databasexml")
    echo "Start diff from $2 ..."
    echo "<== scenario files ==>"
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    DatabaseXMLfiles | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--ito DatabaseXMLfiles--",d,"----------"}{{for(k = 2; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "dda")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    ddacifxfer/src ddacifxfer/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoddacifxfer src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "cca")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    ccacifxfer/src ccacifxfer/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoccacifxfer src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "ccms")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    ccms/src ccms/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoCCMS src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "afautopay")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    afautopay/src afautopay/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoafautopay src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "adjustments")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    adjustments/src adjustments/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoadjustments src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l|awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
  "chances")
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    chancestool/src chancestool/war | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoChancesTool src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l | awk '{print $0-1}'
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag \
    chancesanalysisengine/src/main/java chancesanalysisengine/src/main/webapp chancesanalysisengine/war/WEB-INF/config | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--itoChancesAnalysisEngine java/webapp/config--",d,"----------"}{{for(k = 5; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee -a $file | wc -l | awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '/^\-/ {print $0} /^[A-Za-z0-9]/ {print "M    "$0} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-2}'
    ;;
  *)
    echo "Start diff from $2 ..."
    cvs -d $itocvsroot \
    rdiff -s -r $previoustag -r $currenttag "$module" | grep File \
    |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
    'BEGIN{ "date" | getline d; print "--"'"$module"'"-",d,"----------"}{{for(k = 2; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
    | tee $file | wc -l | awk '{print $0-1}'
    echo "Finsh diff with $3 ..."
    echo "Start generating $file"
    cat $file \
    |awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
    ;;
esac
