#!/usr/bin/bash
# This script is used for codes updated in ito-CVS daily
echo "Rationale is cvs co/up project folder"
echo ""
itocvsroot=":ext:bbu@ito-as1.1fb.net:/vb/cvs"
latestCVS="/cygdrive/d/ITOCVS-Latest"
brchCVS="/cygdrive/d/ITOCVS-Brch"

if [ ! -d $latestCVS ]
  then
	mkdir $latestCVS
	source ~/bin/go $latestCVS
	cvs -d $itocvsroot co -P cs afcollagent afcsragent afshared fsagent fscm fsshared services afservice \
	chancestool chancesanalysisengine outputXmlFiles DatabaseXMLfiles fssplashcontent \
	ccms afautopay adjustments autopayservice ccmsservice emailservice accountservice textbankingservice ddacifxfer ccacifxfer phoneprocessor 
else
	source ~/bin/go $latestCVS
	cvs -d $itocvsroot up -A -d -P cs afcollagent afcsragent afshared fsagent fscm fsshared services chancestool chancesanalysisengine \
	afservice outputXmlFiles DatabaseXMLfiles fssplashcontent ccms afautopay adjustments autopayservice \
	ccmsservice emailservice accountservice textbankingservice ddacifxfer ccacifxfer phoneprocessor 
fi

if [ ! -d $brchCVS ]
  then
	mkdir $brchCVS
	source ~/bin/go $brchCVS
#	cvs -d $itocvsroot co -P -r AFF_3_60 afcollagent afcsragent afshared
	cvs -d $itocvsroot co -P -r AFF_3_60_CAT1 services fsshared
	cvs -d $itocvsroot co -P -r FS_7_50 fscm fssplashcontent
	mkdir fs_fsshared && fs_services
	cvs -d $itocvsroot co -P -d fs_fsshared -r FS_7_50 fsshared
	cvs -d $itocvsroot co -P -d fs_services -r FS_7_50 services
else
	source ~/bin/go $brchCVS
	if [ ! -d fs_fsshared ]
	  then
	  	mkdir fs_fsshared
		cvs -d $itocvsroot co -P -d fs_fsshared -r FS_7_50 fsshared
	fi
	if [ ! -d fs_services ]
	  then
	  	mkdir fs_services
		cvs -d $itocvsroot co -P -d fs_services -r FS_7_50 services
	fi
#	cvs -d $itocvsroot up -d -P -r AFF_3_60 afcollagent afcsragent afshared
	cvs -d $itocvsroot up -d -P -r AFF_3_60_CAT1 services fsshared
	cvs -d $itocvsroot up -d -P -r FS_7_50 fscm fssplashcontent
	source ~/bin/go fs_fsshared && cvs -d $itocvsroot up -d -P -r FS_7_50  && source ~/bin/go $brchCVS
	source ~/bin/go fs_services && cvs -d $itocvsroot up -d -P -r FS_7_50  && source ~/bin/go $brchCVS
fi