#!/usr/bin/bash
# This script is used for simple check whether any roll back codes when drafting file list, especially for prject CAT release final file list
echo "For CAT release final file list, define preTag as last CAT and this script Must be used !!AFTER chkin/build/deploy and just BEFORE drafting!"
echo ""
echo "Rationale is cvs rdiff -r -s tagname -r HEAD project folder, then check out the files and use external tool to compare whether any roll-back exists!"
echo ""
echo "first param is ito cvs module (cs/af/fs750/fs/services/ouputxml/databasexml/afservice ...)"
echo "second param is the previous tag name(e.g. BLEUM_AFFINITY_CAT4_11012011_1)"
echo "third param is the target tag name you want to update to ( usually Head or: BLEUM_AFFINITY_CAT1_07272012_1 )"
echo ""
module=$1
previoustag=$2
currenttag=$3
bleumcvsroot=":sspi:jack.wang@192.168.2.200:/1fb"
prefolder=~/roll-back/Pre
nowfolder=~/roll-back/Now
file=~/roll-back-check_filelist.txt

function rollback-check ()
{
echo "Start diff the file changes ..."
cvs -d $bleumcvsroot \
rdiff -s -r $2 -r $3 \
"$1" | grep -v " is removed" | grep -v " is new"| grep File |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} ' \
|awk -F ' changed' '{print $1}' | tee $file | wc -l|awk '{print $0}'
echo "initialize roll-back check folder..."
rm -rf $prefolder $nowfolder && mkdir -p $prefolder $nowfolder
source go $prefolder
echo "checking out "$previoustag" ..."
cat $file | xargs -i cvs -d $bleumcvsroot co -r $previoustag "{}"
echo "initialize roll-back check folder..."
source go $nowfolder
echo "checking out "$currenttag" ..."
cat $file | xargs -i cvs -d $bleumcvsroot co -r $currenttag "{}"
echo "checking out finished.."
echo "please use external diff tools to compare the folders and pay attention to the '=' and similar'=' marked files, they may be roll back files"
echo ""
echo "roll back files shall NOT be included in final file list"
}

case $module in
  "af")
			rollback-check "affinity/sourcecode/afcollagent/src affinity/sourcecode/afcollagent/war affinity/sourcecode/afcsragent/src affinity/sourcecode/afcsragent/war affinity/sourcecode/afshared/src affinity/sourcecode/afshared/war" \
			$previoustag $currenttag
			;;
  "cs")
			rollback-check "csmaintenance/3.50/SourceCodeUBS/src csmaintenance/3.50/SourceCodeUBS/war" \
			$previoustag $currenttag
			;;
  "services")
			rollback-check "services/Sourcecode/src services/Sourcecode/mapping" \
			$previoustag $currenttag
			;;
  "fs750")
			rollback-check "fs/Sourcecode/fscm/src fs/Sourcecode/fscm/war fs/Sourcecode/fsshared/src fs/Sourcecode/fssplashcontent/src fs/Sourcecode/fssplashcontent/war services/Sourcecode/src services/Sourcecode/mapping" \
			$previoustag $currenttag
			;;			
	*)
			rollback-check "$module" $previoustag $currenttag
			;;
esac


