#!/usr/bin/bash
# This script is used for codes updated in local-CVS daily
echo "Rationale is cvs co/up project folder"
echo ""
echo "Make sure delete whole folder and make script check out project again if you want script a clean run; do NOT only delete all files in the folder but keep an empty folder still, the script will judge this as folder existing and directly do update then, obviously the process will fail, sicne there is no CVS folder at all!"
echo ""
cvsroot=":sspi:jack.wang@192.168.2.200:/1fb"
bcvs="/cygdrive/d/BleumCVS"
jkcvs="/cygdrive/d/JKCVS"

if [ ! -d $bcvs ]
  then
	mkdir $bcvs
	source ~/bin/go $bcvs
	cvs -d $cvsroot co -P 1fbodc OpenProperty affinity csmaintenance fs services
else
	source ~/bin/go $bcvs
	cvs -d $cvsroot up -A -d -P 1fbodc OpenProperty affinity csmaintenance fs services
fi

if [ ! -d $jkcvs ]
  then
	mkdir $jkcvs
	source ~/bin/go $jkcvs
#	cvs -d $cvsroot co -P -r AFF_3_60 affinity/sourcecode/afcollagent affinity/sourcecode/afcsragent affinity/sourcecode/afshared
#	cvs -d $cvsroot co -P -r CS_8_16 csmaintenance/3.50/SourceCodeUBS
#	cvs -d $cvsroot co -P -r AFF_3_60_CAT1 services/Sourcecode fs/Sourcecode/fsshared/src
#	cvs -d $cvsroot co -P -r FS_7_50 fs/Sourcecode/fscm/src fs/Sourcecode/fscm/war fs/Sourcecode/fssplashcontent/src fs/Sourcecode/fssplashcontent/war
#	mkdir fs_fsshared && fs_services
#	cvs -d $cvsroot co -P -d fs_fsshared -r FS_7_50 fs/Sourcecode/fsshared/src
#	cvs -d $cvsroot co -P -d fs_services -r FS_7_50 services
else
	source ~/bin/go $jkcvs
#	cvs -d $cvsroot up -d -P -r AFF_3_60 affinity/sourcecode/afcollagent affinity/sourcecode/afcsragent affinity/sourcecode/afshared 
#	cvs -d $cvsroot up -d -P -r CS_8_16 csmaintenance/3.50/SourceCodeUBS
#	cvs -d $cvsroot up -d -P -r AFF_3_60_CAT1 services/Sourcecode fs/Sourcecode/fsshared/src
#   cvs -d $cvsroot up -d -P -r FS_7_50 fs/Sourcecode/fscm/src fs/Sourcecode/fscm/war fs/Sourcecode/fssplashcontent/src fs/Sourcecode/fssplashcontent/war
	# if [ ! -d fs_fsshared ]
	  # then
	  	# mkdir fs_fsshared
		# cvs -d $cvsroot co -P -d fs_fsshared -r FS_7_50 fs/Sourcecode/fsshared/src
	# else
		# source ~/bin/go fs_fsshared && cvs -d $cvsroot up -d -P -r FS_7_50 && source ~/bin/go $jkcvs
	# fi
	# if [ ! -d fs_services ]
	  # then
	  	# mkdir fs_services
		# cvs -d $cvsroot co -P -d fs_services -r FS_7_50 services
	# else
		# source ~/bin/go fs_services && cvs -d $cvsroot up -d -P -r FS_7_50 && source ~/bin/go $jkcvs
	# fi
fi