#!/usr/bin/bash
# This script is used for generating the final excel list for developer
echo "Rationale is cat <filelist> |grep -v '\[.*files\]' | sort -u | awk '/^[A-Za-z]/ {print $0}' > <output file>"
echo ""
cat result-cs-src.txt | awk '{print $2}' | awk '{print "csmaintenance/3.50/SourceCodeUBS/src/"$0}' > src.txt
while read LINE
do cat result-cs-src.txt | cvs -d :sspi:jack.wang@192.168.2.200:/1fb rlog -N -rCS_7_90. $LINE |awk -F"author: " '{print $2}' \
| awk -F ";" '/^[A-Za-z0-9]/ {print $1}'
done < src.txt | paste result-cs-src.txt - > final.txt
cat final.txt | sed 's/A    /A\t/g' | sed 's/\"/\"\t/g'> final.txt && UNIX2dos -k -n final.txt final.dos.txt
