#!/usr/bin/bash
# This script is used for simple check whether any roll back codes when drafting file list, especially for prject CAT release final file list
echo "For CAT release final file list, define preTag as last CAT and this script Must be used !!AFTER chkin/build/deploy and just BEFORE drafting!!"
echo ""
echo "Rationale is cvs rdiff -r -s tagname -r HEAD project folder, then check out the files and use external tool to compare whether any roll-back exists!"
echo ""
echo "first param is ito cvs module (cs/af/fs750/fs/services/ouputxml/databasexml/afservice ...)"
echo "second param is the previous tag name(e.g. BLEUM_AFFINITY_CAT4_11012011_1)"
echo "third param is the target tag name you want to update to ( usually Head or: BLEUM_AFFINITY_CAT1_07272012_1 )"
echo ""
module=$1
previoustag=$2
currenttag=$3
bleumcvsroot=":sspi:jack.wang@192.168.2.200:/1fb"
dir=~/roll-back_`date +%Y-%m-%d-%H-%M-%S`
prefolder=$dir/Pre-"$2"
nowfolder=$dir/Now-"$3"
file=$dir/roll-back-check_filelist-changes.txt
file1=$dir/roll-back-check_filelist-pre.txt
file2=$dir/roll-back-check_filelist-now.txt

function rollback-check ()
{
echo "Start diff the file between "$previoustag" and "$currenttag" ..."
cvs -d $bleumcvsroot \
rdiff -s -r $2 -r $3 \
"$1" | grep -v " is removed" | grep -v " is new"| grep File |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} ' \
|awk -F ' changed' '{print $1}' | tee $file | wc -l|awk '{print "changed: "$0}'
cp $file $file1 
cvs -d $bleumcvsroot \
rdiff -s -r $2 -r $3 \
"$1" | grep " is removed" | grep File |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} ' \
|awk -F ' is' '{print $1}' | tee -a $file1 | wc -l|awk '{print "removed: "$0}'
cp $file $file2 
cvs -d $bleumcvsroot \
rdiff -s -r $2 -r $3 \
"$1" | grep " is new" | grep File |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} ' \
|awk -F ' is' '{print $1}' | tee -a $file2 | wc -l|awk '{print "added: "$0}'
echo "initialize roll-back check folder of preTag..."
source ~/bin/go $prefolder
echo "checking out "$previoustag" ..."
cat $file1 | xargs -i cvs -d $bleumcvsroot co -r $previoustag "{}"
echo "initialize roll-back check folder of curTag..."
source ~/bin/go $nowfolder
echo "checking out "$currenttag"..."
cat $file2 | xargs -i cvs -d $bleumcvsroot co -r $currenttag "{}"
echo "checking out finished.."
echo "please use external diff tools to compare '$dir' and pay attention to the '=' marked files --> roll back files and 'similar=' --> may be roll back files, be careful!"
echo ""
echo "roll back files shall NOT be included in final file list."
echo "'$1' finished."
source ~/bin/go $dir
mv -f $file "$4"-changes.txt && mv -f $file1 "$4"-pre.txt && mv -f $file2 "$4"-now.txt
echo ""
}

case $module in
  "af")
			mkdir -p $prefolder $nowfolder
			for target_module in "affinity/sourcecode/afcollagent/src" "affinity/sourcecode/afcollagent/war" "affinity/sourcecode/afcsragent/src" "affinity/sourcecode/afcsragent/war" "affinity/sourcecode/afshared/src" "affinity/sourcecode/afshared/war"
			do
			target_folder=`echo $target_module | awk -F '/' '{print $3"-"$4}'`
			rollback-check $target_module $previoustag $currenttag $target_folder
			done
			;;
  "cs")
			mkdir -p $prefolder $nowfolder
			for target_module in "csmaintenance/3.50/SourceCodeUBS/src" "csmaintenance/3.50/SourceCodeUBS/war"
			do
			target_folder=`echo $target_module | awk -F '/' '{print "cs-"$4}'`			
			rollback-check $target_module $previoustag $currenttag $target_folder
			done
			;;
  "services")
			mkdir -p $prefolder $nowfolder
			for target_module in "services/Sourcecode/src" "services/Sourcecode/mapping"
			do
			target_folder=`echo $target_module | awk -F '/' '{print $1"-"$3}'`
			rollback-check $target_module $previoustag $currenttag $target_folder
			done
			;;
  "af360")
			mkdir -p $prefolder $nowfolder
			for target_module in "affinity/sourcecode/afcollagent/src" "affinity/sourcecode/afcollagent/war" "affinity/sourcecode/afcsragent/src" "affinity/sourcecode/afcsragent/war" "affinity/sourcecode/afshared/src" "affinity/sourcecode/afshared/war" "fs/Sourcecode/fsshared/src" "services/Sourcecode/src" "services/Sourcecode/mapping"
			do
			case $target_module in
			 "services/Sourcecode/src")	
				target_folder=`echo $target_module | awk -F '/' '{print $1"-"$3}'`
				;;
			 "services/Sourcecode/mapping")	
				target_folder=`echo $target_module | awk -F '/' '{print $1"-"$3}'`
				;;
			 *)
				target_folder=`echo $target_module | awk -F '/' '{print $3"-"$4}'`
				;;
			esac
			rollback-check $target_module $previoustag $currenttag $target_folder
			done
			;;			
  "fs750")
			mkdir -p $prefolder $nowfolder
			for target_module in "fs/Sourcecode/fscm/src" "fs/Sourcecode/fscm/war" "fs/Sourcecode/fsshared/src" "fs/Sourcecode/fssplashcontent/src" "fs/Sourcecode/fssplashcontent/war" "services/Sourcecode/src" "services/Sourcecode/mapping"
			do
			case $target_module in
			 "services/Sourcecode/src")	
				target_folder=`echo $target_module | awk -F '/' '{print $1"-"$3}'`
				;;
			 "services/Sourcecode/mapping")	
				target_folder=`echo $target_module | awk -F '/' '{print $1"-"$3}'`
				;;
			 *)
				target_folder=`echo $target_module | awk -F '/' '{print $3"-"$4}'`
				;;
			esac
			rollback-check $target_module $previoustag $currenttag $target_folder
			done
			;;
  "fs")
			mkdir -p $prefolder $nowfolder
			for target_module in "fs/Sourcecode/fsagent/src" "fs/Sourcecode/fsagent/war" "fs/Sourcecode/fscm/src" "fs/Sourcecode/fscm/war" "fs/Sourcecode/fsshared/src"
			do
			target_folder=`echo $target_module | awk -F '/' '{print $3"-"$4}'`
			rollback-check $target_module $previoustag $currenttag $target_folder
			done
			;;
	*)
			mkdir -p $prefolder $nowfolder
			target_folder=`echo "$module" | awk -F '/' '{print $(NF-1)"-"$NF}'`
			rollback-check "$module" $previoustag $currenttag "$target_folder"
			;;
esac