#!/usr/bin/bash
# This script is used for simple check whether any codes updated in ito-CVS when generating file list
echo "Rationale is cvs rdiff -r -s tagname -r HEAD project folder"
echo ""
echo "Please Link to VPN first!"
echo "first param is ito cvs module (cs/af/fs750/fs/services/ouputxml/databasexml/afservice ...)"
echo "second param is the previous tag name(e.g. BLEUM_CS_RC_08212012_1)"
echo "third param is the target tag name you want to update to ( usually Head )"
echo ""
module=$1
previoustag=$2
currenttag=$3
file=~/update_filelist_ito.txt
itocvsroot=":ext:bbu@ito-as1.1fb.net:/vb/cvs"

if [ $module = "cs" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
cs/src cs/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoCS src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "af" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
afcollagent/src afcollagent/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoAFcoll src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
afcsragent/src afcsragent/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoAFcsr src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee -a $file | wc -l|awk '{print $0-1}'
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
afshared/src afshared/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoAFShared src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee -a $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '/^\-/ {print $0} /^[A-Za-z0-9]/ {print "M    "$0} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-3}'
fi

if [ $module = "afservice" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
afservice/src | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoafservice src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "services" ]
  then
echo "Start diff from $2 ..."
echo "ignore com/onefbusa/services/common/external/biz/channel/textbanking/ThruDatable.java"
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
services/src services/mapping | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoServices src/mapping--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "fs750" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
fscm/src fscm/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoFscm src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
fsshared/src | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoFsshared src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee -a $file | wc -l|awk '{print $0-1}'
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
fssplashcontent/src fssplashcontent/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoFssplashcontent src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee -a $file | wc -l|awk '{print $0-1}'
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
services/src services/mapping | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoservices src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee -a $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '/^\-/ {print $0} /^[A-Za-z0-9]/ {print "M    "$0} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-4}'
fi

if [ $module = "fs" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
fsagent/src fsagent/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoFsagent src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
fscm/src fscm/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoFscm src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee -a $file | wc -l|awk '{print $0-1}'
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
fsshared/src | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoFsshared src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee -a $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '/^\-/ {print $0} /^[A-Za-z0-9]/ {print "M    "$0} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-3}'
fi

if [ $module = "fssplashcontent" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
fssplashcontent/src fssplashcontent/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoFssplashcontent src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "textbankingservice" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
textbankingservice/src | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itotextbankingservice src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "emailservice" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
emailservice/src | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoemailservice src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "autopayservice" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
autopayservice/src | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoautopayservice src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "accountservice" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
accountservice/src | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoautopayservice src--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "phoneprocessor" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
phoneprocessor/src phoneprocessor/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itophoneprocessor src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "outputxml" ]
  then
echo "Start diff from $2 ..."
echo "current we only focus on: 1fbbizprocess, ftebizprocess, accountbizprocess, autopaybizprocess, emailbizprocess "
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
outputXmlFiles | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--ito outputXmlFiles--",d,"----------"}{{for(k = 2; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "databasexml" ]
  then
echo "Start diff from $2 ..."
echo "<== scenario files ==>"
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
DatabaseXMLfiles | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--ito DatabaseXMLfiles--",d,"----------"}{{for(k = 2; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "dda" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
ddacifxfer/src ddacifxfer/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoddacifxfer src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "cca" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
ccacifxfer/src ccacifxfer/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoccacifxfer src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "ccms" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
ccms/src ccms/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoCCMS src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "afautopay" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
afautopay/src afautopay/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoafautopay src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi

if [ $module = "adjustments" ]
  then
echo "Start diff from $2 ..."
cvs -d $itocvsroot \
rdiff -s -r $previoustag -r $currenttag \
adjustments/src adjustments/war | grep File \
|awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} '|awk -F '/' \
'BEGIN{ "date" | getline d; print "--itoadjustments src/war--",d,"----------"}{{for(k = 3; k<NF; k++) printf "%s/",$k} printf "%s\n",$k}' \
| tee $file | wc -l|awk '{print $0-1}'
echo "Finsh diff with $3 ..."
echo "Start generating $file"
cat $file \
|awk '{if (NR!=1) {print "M    "$0}else {print $0}} END{ while (getline < "/home/jack.wang/update_filelist_ito.txt" > 0) lc++; print "----the total filelist number:"lc-1}'
fi