#!/usr/bin/bash
# This script is used for simple check whether any roll back codes when drafting file list, especially for prject CAT release final file list
echo "For CAT release final file list, define preTag as last CAT and this script Must be used !!AFTER chkin/build/deploy and just BEFORE drafting!"
echo ""
echo "Rationale is cvs rdiff -r -s tagname -r HEAD project folder, then check out the files and use external tool to compare whether any roll-back exists!"
echo ""
echo "first param is ito cvs module (cs/af/fs750/fs/services/ouputxml/databasexml/afservice ...)"
echo "second param is the previous tag name(e.g. BLEUM_AFFINITY_CAT4_11012011_1)"
echo "third param is the target tag name you want to update to ( usually Head or: BLEUM_AFFINITY_CAT1_07272012_1 )"
echo ""
module=$1
previoustag=$2
currenttag=$3
itocvsroot=":ext:bbu@ito-as1.1fb.net:/vb/cvs"
prefolder=~/roll-back/Pre-ito-"$2"
nowfolder=~/roll-back/Now-ito-"$3"
file=~/roll-back/roll-back-check_filelist-ito-changes.txt
file1=~/roll-back/roll-back-check_filelist-ito-pre.txt
file2=~/roll-back/roll-back-check_filelist-ito-now.txt

function rollback-check ()
{
echo "Start diff the file between "$previoustag" and "$currenttag" ..."
cvs -d $itocvsroot \
rdiff -s -r $2 -r $3 \
"$1" | grep -v " is removed" | grep -v " is new"| grep File |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} ' \
|awk -F ' changed' '{print $1}' | tee $file | wc -l|awk '{print "changed: "$0}'
cp $file $file1 
cvs -d $itocvsroot \
rdiff -s -r $2 -r $3 \
"$1" | grep " is removed" | grep File |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} ' \
|awk -F ' is' '{print $1}' | tee -a $file1 | wc -l|awk '{print "removed: "$0}'
cp $file $file2 
cvs -d $itocvsroot \
rdiff -s -r $2 -r $3 \
"$1" | grep " is new" | grep File |awk '{ {for(j = 2; j<NF; j++) printf "%s ",$j} printf "%s\n",$j} ' \
|awk -F ' is' '{print $1}' | tee -a $file2 | wc -l|awk '{print "added: "$0}'
echo "initialize roll-back check folder..."
source go $prefolder
echo "checking out "$previoustag" ..."
cat $file1 | xargs -i cvs -d $itocvsroot co -r $previoustag "{}"
echo "initialize roll-back check folder..."
source go $nowfolder
echo "checking out "$currenttag" ..."
cat $file2 | xargs -i cvs -d $itocvsroot co -r $currenttag "{}"
echo "checking out finished.."
echo "please use external diff tools to compare the folders and pay attention to the '=' marked files, they may be roll back files"
echo ""
echo "roll back files shall NOT be included in final file list"
}

case $module in
  "af")
			rm -rf $prefolder $nowfolder && mkdir -p $prefolder $nowfolder
			for target_module in "afcollagent/src" "afcollagent/war" "afcsragent/src" "afcsragent/war" "afshared/src" "afshared/war"
			do
			rollback-check $target_module $previoustag $currenttag
			done
			;;
  "cs")
			rm -rf $prefolder $nowfolder && mkdir -p $prefolder $nowfolder
			for target_module in "cs/src" "cs/war"
			do
			rollback-check $target_module $previoustag $currenttag
			done
			;;
  "services")
			rm -rf $prefolder $nowfolder && mkdir -p $prefolder $nowfolder
			for target_module in "services/src" "services/mapping"
			do
			rollback-check $target_module $previoustag $currenttag
			done  
			;;
  "fs750")
			rm -rf $prefolder $nowfolder && mkdir -p $prefolder $nowfolder
			for target_module in "fscm/src" "fscm/war" "fsshared/src" "fssplashcontent/src" "fssplashcontent/war" "services/src" "services/mapping"
			do
			rollback-check $target_module $previoustag $currenttag
			done
			;;
  "fs")
			rm -rf $prefolder $nowfolder && mkdir -p $prefolder $nowfolder
			for target_module in "fsagent/src" "fsagent/war" "fscm/src" "fscm/war" "fsshared/src"
			do
			rollback-check $target_module $previoustag $currenttag
			done
			;;
	*)
			rm -rf $prefolder $nowfolder && mkdir -p $prefolder $nowfolder
			rollback-check "$module" $previoustag $currenttag
			;;
esac