#!/usr/bin/bash
# pull and push files from cygwin.home to github
echo "first param is path you wanna sync with github (cygwin.home/bin..)"
echo "second param is the range of modified time usually 1 day"

path=$1
range=$2
git_dir="/home/jack.wang/git"
git_remote="git@github.com:olddoggie/git.git"

function git-pull-push ()
{ 
git pull && git add -A && git commit -m 'update from 152' && git push 
}

case $1 in
  "bin")
		cp -u "/home/jack.wang/.bashrc" "/home/jack.wang/bin"
	  	find /home/jack.wang/bin/ -type f -mtime -$2 | xargs -i cp {} "${git_dir}/cyg-putty shell scripts"
		source /home/jack.wang/bin/go "${git_dir}"
		git-pull-push
		find "${git_dir}/cyg-putty shell scripts" -type f -mtime -$2 | xargs -i cp {} /home/jack.wang/bin
		cp -u "/home/jack.wang/bin/.bashrc" "/home/jack.wang"
			;;
	*)
			echo "No such kind of ant scirpt .."
			exit 1
			;;
esac
