#!/usr/bin/env python
from urllib2 import urlopen
from urllib import urlencode

import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import json

# The new words memorandum here: 
myfile = file("/home/jack.wang/Word-Memo.txt", 'a')

# The google translate API can be found here: 
# http://code.google.com/apis/ajaxlanguage/documentation/#Examples

source=sys.argv[1]
target=sys.argv[2]
text=' '.join(sys.argv[3:])
key='wp2dubhiWi7Xqs0pP5uQSouB'

#base_url='https://www.googleapis.com/language/translate/v2?'
base_url=' http://openapi.baidu.com/public/2.0/bmt/translate?'

#params=urlencode( (('key', key), ('q',text), ('source',source), ('target',target)) )				   
params=urlencode( (('client_id', key), ('q',text), ('from',source), ('to',target)) )
				   
url=base_url+params
content=urlopen(url).read()
#print content
jdata=json.loads(content)
for key,value in jdata.iteritems():
    if key == "trans_result":
		trans_result = value[0]
		for key, value in trans_result.iteritems():
			if key == "dst": print '\033[35;33m%s\033[0m' %(value) ; print >>myfile, value
myfile.close()